language: ruby
rvm:
  - 2.2.3
before_install:
  - npm install -g npm@3.x-latest
  - gem install bundler
  - "rm ${BUNDLE_GEMFILE}.lock"
  - curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar xz -C /tmp
  - cd /tmp/beanstalkd-1.10/
  - make
  - ./beanstalkd &
  - cd $TRAVIS_BUILD_DIR
before_script:
  - bundle install
  - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
cache: bundler
